import type { MeetingType } from './types'

export interface SlideTemplate {
  number: number
  titleFr: string
  titleEn: string
  descriptionFr: string
  descriptionEn: string
  tipFr: string
  tipEn: string
}

export interface PresentationTemplate {
  meetingType: MeetingType
  totalSlides: number
  durationMinFr: string
  durationMinEn: string
  slides: SlideTemplate[]
}

export const TEMPLATES: PresentationTemplate[] = [
  {
    meetingType: 'comite-direction',
    totalSlides: 12,
    durationMinFr: '20-30 min',
    durationMinEn: '20-30 min',
    slides: [
      {
        number: 1,
        titleFr: 'Page de titre',
        titleEn: 'Title Slide',
        descriptionFr: 'Titre du sujet, date, auteur, classification du document.',
        descriptionEn: 'Subject title, date, author, document classification.',
        tipFr: 'Soyez précis dans le titre : il doit annoncer la décision attendue.',
        tipEn: 'Be precise in the title: it should announce the expected decision.',
      },
      {
        number: 2,
        titleFr: 'Executive Summary',
        titleEn: 'Executive Summary',
        descriptionFr: 'Résumé en 3-5 bullet points : contexte, enjeu, recommandation, décision attendue.',
        descriptionEn: 'Summary in 3-5 bullet points: context, stakes, recommendation, expected decision.',
        tipFr: 'Le comité doit comprendre l\'essentiel en 30 secondes sur cette slide.',
        tipEn: 'The board must understand the essentials in 30 seconds on this slide.',
      },
      {
        number: 3,
        titleFr: 'Contexte et enjeux',
        titleEn: 'Context & Stakes',
        descriptionFr: 'Pourquoi ce sujet est porté au comité. Rappel du contexte stratégique.',
        descriptionEn: 'Why this topic is brought to the board. Strategic context reminder.',
        tipFr: 'Restez factuel et lié à la stratégie de l\'entreprise.',
        tipEn: 'Stay factual and linked to company strategy.',
      },
      {
        number: 4,
        titleFr: 'Analyse de la situation',
        titleEn: 'Situation Analysis',
        descriptionFr: 'Données clés, faits et chiffres qui éclairent la décision.',
        descriptionEn: 'Key data, facts and figures that inform the decision.',
        tipFr: 'Distinguez clairement faits, analyses et opinions.',
        tipEn: 'Clearly distinguish facts, analyses and opinions.',
      },
      {
        number: 5,
        titleFr: 'Options et analyse comparative',
        titleEn: 'Options & Comparative Analysis',
        descriptionFr: 'Tableau comparatif des options avec critères : coût, délai, risque, ROI.',
        descriptionEn: 'Comparative table of options with criteria: cost, timeline, risk, ROI.',
        tipFr: 'Un tableau côte à côte est plus efficace qu\'un texte pour comparer.',
        tipEn: 'A side-by-side table is more effective than text for comparison.',
      },
      {
        number: 6,
        titleFr: 'Recommandation',
        titleEn: 'Recommendation',
        descriptionFr: 'Option recommandée avec justification synthétique et impacts attendus.',
        descriptionEn: 'Recommended option with brief justification and expected impacts.',
        tipFr: 'Formulez clairement : « Nous recommandons l\'option X parce que… ».',
        tipEn: 'State clearly: "We recommend option X because...".',
      },
      {
        number: 7,
        titleFr: 'Impacts financiers',
        titleEn: 'Financial Impacts',
        descriptionFr: 'Budget requis, ROI estimé, impact P&L.',
        descriptionEn: 'Required budget, estimated ROI, P&L impact.',
        tipFr: 'Chiffrez systématiquement. Le comité décide sur des données concrètes.',
        tipEn: 'Always quantify. The board decides based on concrete data.',
      },
      {
        number: 8,
        titleFr: 'Risques et mitigations',
        titleEn: 'Risks & Mitigations',
        descriptionFr: 'Top 3-5 risques avec probabilité, impact et plan de mitigation.',
        descriptionEn: 'Top 3-5 risks with probability, impact and mitigation plan.',
        tipFr: 'Ne cachez pas les risques — le comité appréciera votre transparence.',
        tipEn: 'Don\'t hide risks — the board will appreciate your transparency.',
      },
      {
        number: 9,
        titleFr: 'Planning macro',
        titleEn: 'High-level Timeline',
        descriptionFr: 'Jalons clés et grandes phases du projet si la décision est prise.',
        descriptionEn: 'Key milestones and major phases if the decision is approved.',
        tipFr: 'Restez au niveau macro. Les détails opérationnels ne sont pas pour le comité.',
        tipEn: 'Stay high-level. Operational details are not for the board.',
      },
      {
        number: 10,
        titleFr: 'Demande de décision',
        titleEn: 'Decision Request',
        descriptionFr: 'Formulation explicite de ce qui est demandé au comité : approbation, budget, Go/No-Go.',
        descriptionEn: 'Explicit formulation of what is asked: approval, budget, Go/No-Go.',
        tipFr: 'Soyez direct et spécifique. Évitez « Qu\'en pensez-vous ? » — formulez la décision.',
        tipEn: 'Be direct and specific. Avoid "What do you think?" — formulate the decision.',
      },
      {
        number: 11,
        titleFr: 'Prochaines étapes',
        titleEn: 'Next Steps',
        descriptionFr: 'Actions immédiates avec responsables, délais et critères de succès.',
        descriptionEn: 'Immediate actions with owners, deadlines and success criteria.',
        tipFr: 'Chaque action doit avoir un responsable nommé et une date.',
        tipEn: 'Each action must have a named owner and a date.',
      },
      {
        number: 12,
        titleFr: 'Annexes',
        titleEn: 'Appendix',
        descriptionFr: 'Données détaillées, sources, analyses complémentaires.',
        descriptionEn: 'Detailed data, sources, supplementary analyses.',
        tipFr: 'Les annexes sont là pour répondre aux questions, pas pour être présentées.',
        tipEn: 'Appendices are there to answer questions, not to be presented.',
      },
    ],
  },
  {
    meetingType: 'kick-off',
    totalSlides: 14,
    durationMinFr: '45-60 min',
    durationMinEn: '45-60 min',
    slides: [
      {
        number: 1,
        titleFr: 'Page de titre',
        titleEn: 'Title Slide',
        descriptionFr: 'Nom du projet, date de kick-off, sponsor et chef de projet.',
        descriptionEn: 'Project name, kick-off date, sponsor and project manager.',
        tipFr: 'Incluez le logo du projet si disponible pour créer une identité.',
        tipEn: 'Include the project logo if available to create an identity.',
      },
      {
        number: 2,
        titleFr: 'Agenda',
        titleEn: 'Agenda',
        descriptionFr: 'Plan de la session avec les sujets et durées estimées.',
        descriptionEn: 'Session plan with topics and estimated durations.',
        tipFr: 'Permet aux participants de savoir ce qui les attend.',
        tipEn: 'Lets participants know what to expect.',
      },
      {
        number: 3,
        titleFr: 'Pourquoi ce projet ?',
        titleEn: 'Why This Project?',
        descriptionFr: 'Contexte business, problème à résoudre, opportunité à saisir.',
        descriptionEn: 'Business context, problem to solve, opportunity to seize.',
        tipFr: 'Le « pourquoi » motive l\'équipe. Reliez le projet à la stratégie.',
        tipEn: 'The "why" motivates the team. Link the project to strategy.',
      },
      {
        number: 4,
        titleFr: 'Objectifs du projet',
        titleEn: 'Project Objectives',
        descriptionFr: 'Objectifs SMART : Spécifiques, Mesurables, Atteignables, Réalistes, Temporels.',
        descriptionEn: 'SMART objectives: Specific, Measurable, Achievable, Realistic, Time-bound.',
        tipFr: 'Chaque objectif doit être vérifiable à la fin du projet.',
        tipEn: 'Each objective must be verifiable at the end of the project.',
      },
      {
        number: 5,
        titleFr: 'Périmètre (In / Out of Scope)',
        titleEn: 'Scope (In / Out of Scope)',
        descriptionFr: 'Ce qui est inclus et ce qui est explicitement exclu du projet.',
        descriptionEn: 'What is included and what is explicitly excluded from the project.',
        tipFr: 'Le out-of-scope est aussi important que l\'in-scope pour éviter les dérives.',
        tipEn: 'Out-of-scope is as important as in-scope to avoid scope creep.',
      },
      {
        number: 6,
        titleFr: 'Parties prenantes',
        titleEn: 'Stakeholders',
        descriptionFr: 'Mapping des parties prenantes avec leur rôle et niveau d\'implication.',
        descriptionEn: 'Stakeholder mapping with roles and involvement level.',
        tipFr: 'Identifiez clairement le sponsor et le décideur final.',
        tipEn: 'Clearly identify the sponsor and final decision-maker.',
      },
      {
        number: 7,
        titleFr: 'Équipe projet et RACI',
        titleEn: 'Project Team & RACI',
        descriptionFr: 'Organigramme de l\'équipe et matrice RACI pour les grandes activités.',
        descriptionEn: 'Team org chart and RACI matrix for major activities.',
        tipFr: 'Chacun doit savoir exactement ce qu\'on attend de lui.',
        tipEn: 'Everyone must know exactly what is expected of them.',
      },
      {
        number: 8,
        titleFr: 'Planning et jalons',
        titleEn: 'Timeline & Milestones',
        descriptionFr: 'Macro-planning avec phases, jalons clés et dates cibles.',
        descriptionEn: 'High-level plan with phases, key milestones and target dates.',
        tipFr: 'Utilisez un diagramme de Gantt simplifié ou une timeline visuelle.',
        tipEn: 'Use a simplified Gantt chart or visual timeline.',
      },
      {
        number: 9,
        titleFr: 'Livrables attendus',
        titleEn: 'Expected Deliverables',
        descriptionFr: 'Liste des livrables par phase avec critères d\'acceptation.',
        descriptionEn: 'List of deliverables per phase with acceptance criteria.',
        tipFr: 'Des livrables bien définis évitent les malentendus en fin de projet.',
        tipEn: 'Well-defined deliverables prevent misunderstandings at project end.',
      },
      {
        number: 10,
        titleFr: 'Budget et ressources',
        titleEn: 'Budget & Resources',
        descriptionFr: 'Enveloppe budgétaire, ressources humaines et matérielles mobilisées.',
        descriptionEn: 'Budget envelope, human and material resources mobilized.',
        tipFr: 'Soyez transparent sur les contraintes budgétaires dès le départ.',
        tipEn: 'Be transparent about budget constraints from the start.',
      },
      {
        number: 11,
        titleFr: 'Risques et hypothèses',
        titleEn: 'Risks & Assumptions',
        descriptionFr: 'Risques identifiés avec plan de mitigation. Hypothèses structurantes.',
        descriptionEn: 'Identified risks with mitigation plan. Key assumptions.',
        tipFr: 'Impliquez l\'équipe dans l\'identification des risques pendant le kick-off.',
        tipEn: 'Involve the team in risk identification during the kick-off.',
      },
      {
        number: 12,
        titleFr: 'Règles de fonctionnement',
        titleEn: 'Operating Rules',
        descriptionFr: 'Rituels (stand-up, revues), outils (Jira, Teams), canaux de communication.',
        descriptionEn: 'Rituals (stand-up, reviews), tools (Jira, Teams), communication channels.',
        tipFr: 'Des règles claires dès le jour 1 évitent les frictions par la suite.',
        tipEn: 'Clear rules from day 1 prevent friction later.',
      },
      {
        number: 13,
        titleFr: 'Prochaines étapes',
        titleEn: 'Next Steps',
        descriptionFr: 'Actions immédiates post kick-off avec responsables et délais.',
        descriptionEn: 'Immediate post kick-off actions with owners and deadlines.',
        tipFr: 'Terminez toujours par des actions concrètes pour maintenir le momentum.',
        tipEn: 'Always end with concrete actions to maintain momentum.',
      },
      {
        number: 14,
        titleFr: 'Questions & Discussion',
        titleEn: 'Questions & Discussion',
        descriptionFr: 'Temps dédié aux questions de l\'équipe et des parties prenantes.',
        descriptionEn: 'Dedicated time for team and stakeholder questions.',
        tipFr: 'Prévoyez 10-15 min. Les questions révèlent les zones d\'ombre.',
        tipEn: 'Plan 10-15 min. Questions reveal blind spots.',
      },
    ],
  },
  {
    meetingType: 'revue-projet',
    totalSlides: 10,
    durationMinFr: '15-25 min',
    durationMinEn: '15-25 min',
    slides: [
      {
        number: 1,
        titleFr: 'Page de titre',
        titleEn: 'Title Slide',
        descriptionFr: 'Nom du projet, date de la revue, période couverte.',
        descriptionEn: 'Project name, review date, period covered.',
        tipFr: 'Indiquez clairement la période (ex : Sprint 14 — 24 fév au 7 mars).',
        tipEn: 'Clearly indicate the period (e.g., Sprint 14 — Feb 24 to Mar 7).',
      },
      {
        number: 2,
        titleFr: 'Dashboard synthétique (RAG)',
        titleEn: 'Summary Dashboard (RAG)',
        descriptionFr: 'Statut global du projet en un coup d\'œil : Scope, Budget, Planning, Qualité (Rouge/Orange/Vert).',
        descriptionEn: 'Overall project status at a glance: Scope, Budget, Timeline, Quality (Red/Amber/Green).',
        tipFr: 'Le sponsor doit comprendre la santé du projet en 10 secondes.',
        tipEn: 'The sponsor must understand project health in 10 seconds.',
      },
      {
        number: 3,
        titleFr: 'Réalisations de la période',
        titleEn: 'Period Achievements',
        descriptionFr: 'Ce qui a été livré ou accompli pendant la période écoulée.',
        descriptionEn: 'What was delivered or accomplished during the past period.',
        tipFr: 'Listez les faits concrets, pas les activités en cours.',
        tipEn: 'List concrete accomplishments, not ongoing activities.',
      },
      {
        number: 4,
        titleFr: 'Avancement vs. Plan',
        titleEn: 'Progress vs. Plan',
        descriptionFr: 'Comparaison entre le planifié et le réalisé. Jalons atteints et écarts.',
        descriptionEn: 'Comparison between planned and actual. Milestones reached and gaps.',
        tipFr: 'Un diagramme de Gantt mis à jour ou une barre de progression visuelle.',
        tipEn: 'An updated Gantt chart or visual progress bar.',
      },
      {
        number: 5,
        titleFr: 'Indicateurs clés (KPIs)',
        titleEn: 'Key Indicators (KPIs)',
        descriptionFr: 'Métriques de suivi : vélocité, consommation budget, qualité.',
        descriptionEn: 'Tracking metrics: velocity, budget consumption, quality.',
        tipFr: 'Les tendances comptent plus que les valeurs absolues.',
        tipEn: 'Trends matter more than absolute values.',
      },
      {
        number: 6,
        titleFr: 'Problèmes et blocages',
        titleEn: 'Issues & Blockers',
        descriptionFr: 'Problèmes rencontrés, impact sur le projet, demandes d\'aide ou d\'escalade.',
        descriptionEn: 'Issues encountered, impact on project, requests for help or escalation.',
        tipFr: 'Pour chaque problème, proposez une recommandation — ne venez pas les mains vides.',
        tipEn: 'For each issue, propose a recommendation — don\'t come empty-handed.',
      },
      {
        number: 7,
        titleFr: 'Risques mis à jour',
        titleEn: 'Updated Risks',
        descriptionFr: 'Nouveaux risques identifiés, évolution des risques existants.',
        descriptionEn: 'Newly identified risks, evolution of existing risks.',
        tipFr: 'Mettez en avant les risques dont le statut a changé.',
        tipEn: 'Highlight risks whose status has changed.',
      },
      {
        number: 8,
        titleFr: 'Décisions nécessaires',
        titleEn: 'Decisions Needed',
        descriptionFr: 'Points nécessitant une décision du comité de pilotage.',
        descriptionEn: 'Points requiring a steering committee decision.',
        tipFr: 'Formulez clairement les options et votre recommandation.',
        tipEn: 'Clearly formulate options and your recommendation.',
      },
      {
        number: 9,
        titleFr: 'Plan des 2 prochaines semaines',
        titleEn: 'Next 2 Weeks Plan',
        descriptionFr: 'Actions planifiées avec responsables et échéances.',
        descriptionEn: 'Planned actions with owners and deadlines.',
        tipFr: 'Soyez spécifique : « Qui fait quoi pour quand ».',
        tipEn: 'Be specific: "Who does what by when".',
      },
      {
        number: 10,
        titleFr: 'Questions',
        titleEn: 'Questions',
        descriptionFr: 'Temps dédié aux questions et clarifications.',
        descriptionEn: 'Dedicated time for questions and clarifications.',
        tipFr: 'Préparez des réponses aux questions prévisibles.',
        tipEn: 'Prepare answers to predictable questions.',
      },
    ],
  },
  {
    meetingType: 'commercial',
    totalSlides: 12,
    durationMinFr: '25-40 min',
    durationMinEn: '25-40 min',
    slides: [
      {
        number: 1,
        titleFr: 'Page de titre',
        titleEn: 'Title Slide',
        descriptionFr: 'Titre orienté bénéfice client, date, équipe commerciale.',
        descriptionEn: 'Client benefit-oriented title, date, sales team.',
        tipFr: 'Le titre doit parler du client, pas de vous. Ex : « Sécuriser votre croissance » plutôt que « Notre offre ».',
        tipEn: 'The title should be about the client, not you. E.g., "Securing your growth" rather than "Our offering".',
      },
      {
        number: 2,
        titleFr: 'Compréhension du client',
        titleEn: 'Client Understanding',
        descriptionFr: 'Contexte du client : secteur, enjeux, défis spécifiques identifiés.',
        descriptionEn: 'Client context: sector, stakes, specific identified challenges.',
        tipFr: 'Montrez que vous avez fait vos devoirs. Le client doit se sentir compris.',
        tipEn: 'Show that you\'ve done your homework. The client must feel understood.',
      },
      {
        number: 3,
        titleFr: 'Le problème',
        titleEn: 'The Problem',
        descriptionFr: 'Formulation du problème ou du besoin client avec impact chiffré si possible.',
        descriptionEn: 'Problem or need formulation with quantified impact if possible.',
        tipFr: 'Quantifiez le coût du problème pour créer l\'urgence.',
        tipEn: 'Quantify the cost of the problem to create urgency.',
      },
      {
        number: 4,
        titleFr: 'Notre approche',
        titleEn: 'Our Approach',
        descriptionFr: 'Vision de la solution et différenciation par rapport aux alternatives.',
        descriptionEn: 'Solution vision and differentiation from alternatives.',
        tipFr: 'Restez orienté bénéfices, pas fonctionnalités.',
        tipEn: 'Stay benefit-oriented, not feature-oriented.',
      },
      {
        number: 5,
        titleFr: 'Proposition de valeur',
        titleEn: 'Value Proposition',
        descriptionFr: 'Bénéfices concrets pour le client : gains, économies, réduction de risque.',
        descriptionEn: 'Concrete benefits for the client: gains, savings, risk reduction.',
        tipFr: 'Utilisez des chiffres et des exemples concrets.',
        tipEn: 'Use numbers and concrete examples.',
      },
      {
        number: 6,
        titleFr: 'Solution détaillée',
        titleEn: 'Detailed Solution',
        descriptionFr: 'Présentation de la solution : composantes, fonctionnement, architecture.',
        descriptionEn: 'Solution overview: components, how it works, architecture.',
        tipFr: 'Adaptez le niveau de détail technique à votre audience.',
        tipEn: 'Adapt the technical detail level to your audience.',
      },
      {
        number: 7,
        titleFr: 'Cas client / Références',
        titleEn: 'Case Study / References',
        descriptionFr: 'Exemples de réussites avec des clients similaires. Résultats mesurables.',
        descriptionEn: 'Success examples with similar clients. Measurable results.',
        tipFr: 'Les preuves sociales sont votre meilleur argument.',
        tipEn: 'Social proof is your strongest argument.',
      },
      {
        number: 8,
        titleFr: 'Plan de déploiement',
        titleEn: 'Deployment Plan',
        descriptionFr: 'Grandes phases, timeline, effort client requis.',
        descriptionEn: 'Major phases, timeline, required client effort.',
        tipFr: 'Rassurez sur la facilité de mise en œuvre.',
        tipEn: 'Reassure about ease of implementation.',
      },
      {
        number: 9,
        titleFr: 'Investissement',
        titleEn: 'Investment',
        descriptionFr: 'Modèle tarifaire, conditions, ROI attendu.',
        descriptionEn: 'Pricing model, terms, expected ROI.',
        tipFr: 'Parlez d\'investissement, pas de coût. Montrez le ROI.',
        tipEn: 'Talk about investment, not cost. Show the ROI.',
      },
      {
        number: 10,
        titleFr: 'Pourquoi nous ?',
        titleEn: 'Why Us?',
        descriptionFr: 'Différenciateurs clés, expertise, engagement qualité.',
        descriptionEn: 'Key differentiators, expertise, quality commitment.',
        tipFr: 'Soyez authentique. Mettez en avant ce qui vous rend réellement unique.',
        tipEn: 'Be authentic. Highlight what truly makes you unique.',
      },
      {
        number: 11,
        titleFr: 'Prochaines étapes',
        titleEn: 'Next Steps',
        descriptionFr: 'Call to action clair : POC, rendez-vous, proposition formelle.',
        descriptionEn: 'Clear call to action: POC, meeting, formal proposal.',
        tipFr: 'Ne terminez jamais sans un call to action précis et daté.',
        tipEn: 'Never end without a precise and dated call to action.',
      },
      {
        number: 12,
        titleFr: 'Coordonnées et contact',
        titleEn: 'Contact Information',
        descriptionFr: 'Coordonnées de l\'équipe commerciale, liens utiles.',
        descriptionEn: 'Sales team contact details, useful links.',
        tipFr: 'Facilitez la prise de contact pour le client.',
        tipEn: 'Make it easy for the client to get in touch.',
      },
    ],
  },
  {
    meetingType: 'formation',
    totalSlides: 14,
    durationMinFr: '60-90 min',
    durationMinEn: '60-90 min',
    slides: [
      {
        number: 1,
        titleFr: 'Page de titre',
        titleEn: 'Title Slide',
        descriptionFr: 'Titre de la formation, formateur, date, durée prévue.',
        descriptionEn: 'Training title, trainer, date, expected duration.',
        tipFr: 'Un titre engageant donne envie d\'apprendre.',
        tipEn: 'An engaging title makes people want to learn.',
      },
      {
        number: 2,
        titleFr: 'Objectifs pédagogiques',
        titleEn: 'Learning Objectives',
        descriptionFr: '« À la fin de cette session, vous saurez… » — 3-5 objectifs concrets.',
        descriptionEn: '"By the end of this session, you will be able to..." — 3-5 concrete objectives.',
        tipFr: 'Formulez avec des verbes d\'action : comprendre, appliquer, configurer.',
        tipEn: 'Use action verbs: understand, apply, configure.',
      },
      {
        number: 3,
        titleFr: 'Agenda de la session',
        titleEn: 'Session Agenda',
        descriptionFr: 'Plan de la formation avec les modules et durées.',
        descriptionEn: 'Training plan with modules and durations.',
        tipFr: 'Indiquez les moments de pause et d\'exercice.',
        tipEn: 'Indicate break and exercise times.',
      },
      {
        number: 4,
        titleFr: 'Prérequis',
        titleEn: 'Prerequisites',
        descriptionFr: 'Ce que les participants doivent savoir ou avoir préparé avant la session.',
        descriptionEn: 'What participants should know or have prepared before the session.',
        tipFr: 'Évitez les frustrations en étant clair sur le niveau attendu.',
        tipEn: 'Avoid frustration by being clear about the expected level.',
      },
      {
        number: 5,
        titleFr: 'Introduction / Concepts clés',
        titleEn: 'Introduction / Key Concepts',
        descriptionFr: 'Définitions et concepts fondamentaux. Glossaire si nécessaire.',
        descriptionEn: 'Definitions and fundamental concepts. Glossary if needed.',
        tipFr: 'Définissez tous les acronymes. Ne supposez jamais que tout le monde les connaît.',
        tipEn: 'Define all acronyms. Never assume everyone knows them.',
      },
      {
        number: 6,
        titleFr: 'Module 1 — Théorie',
        titleEn: 'Module 1 — Theory',
        descriptionFr: 'Premier bloc de contenu. Allez du simple au complexe.',
        descriptionEn: 'First content block. Go from simple to complex.',
        tipFr: 'Utilisez des analogies et des visuels pour expliquer les concepts abstraits.',
        tipEn: 'Use analogies and visuals to explain abstract concepts.',
      },
      {
        number: 7,
        titleFr: 'Module 1 — Exercice pratique',
        titleEn: 'Module 1 — Hands-on Exercise',
        descriptionFr: 'Mise en pratique immédiate du concept enseigné.',
        descriptionEn: 'Immediate practice of the taught concept.',
        tipFr: 'L\'apprentissage est 3x plus efficace avec la pratique immédiate.',
        tipEn: 'Learning is 3x more effective with immediate practice.',
      },
      {
        number: 8,
        titleFr: 'Module 2 — Théorie',
        titleEn: 'Module 2 — Theory',
        descriptionFr: 'Deuxième bloc de contenu, qui s\'appuie sur le module 1.',
        descriptionEn: 'Second content block, building on module 1.',
        tipFr: 'Faites le lien explicite avec le module précédent.',
        tipEn: 'Make the explicit link with the previous module.',
      },
      {
        number: 9,
        titleFr: 'Module 2 — Exercice pratique',
        titleEn: 'Module 2 — Hands-on Exercise',
        descriptionFr: 'Exercice combinant les concepts des modules 1 et 2.',
        descriptionEn: 'Exercise combining concepts from modules 1 and 2.',
        tipFr: 'Proposez un exercice qui intègre les deux modules pour consolider.',
        tipEn: 'Offer an exercise integrating both modules to consolidate.',
      },
      {
        number: 10,
        titleFr: 'Cas pratique complet',
        titleEn: 'Full Case Study',
        descriptionFr: 'Scénario réaliste mettant en œuvre l\'ensemble des apprentissages.',
        descriptionEn: 'Realistic scenario applying all learnings.',
        tipFr: 'Utilisez un cas proche de la réalité métier des participants.',
        tipEn: 'Use a case close to participants\' business reality.',
      },
      {
        number: 11,
        titleFr: 'Erreurs fréquentes / FAQ',
        titleEn: 'Common Mistakes / FAQ',
        descriptionFr: 'Pièges à éviter et réponses aux questions fréquentes.',
        descriptionEn: 'Pitfalls to avoid and answers to frequent questions.',
        tipFr: 'Partager les erreurs courantes accélère l\'apprentissage.',
        tipEn: 'Sharing common mistakes accelerates learning.',
      },
      {
        number: 12,
        titleFr: 'Récapitulatif',
        titleEn: 'Recap',
        descriptionFr: 'Résumé des points clés de la session en une slide.',
        descriptionEn: 'Summary of key session points in one slide.',
        tipFr: 'Reprenez les objectifs du début et montrez qu\'ils sont couverts.',
        tipEn: 'Revisit the initial objectives and show they are covered.',
      },
      {
        number: 13,
        titleFr: 'Ressources complémentaires',
        titleEn: 'Additional Resources',
        descriptionFr: 'Documentation, liens, tutoriels vidéo, contacts support.',
        descriptionEn: 'Documentation, links, video tutorials, support contacts.',
        tipFr: 'Donnez aux participants les moyens de continuer à apprendre seuls.',
        tipEn: 'Give participants the means to continue learning on their own.',
      },
      {
        number: 14,
        titleFr: 'Quiz / Évaluation',
        titleEn: 'Quiz / Assessment',
        descriptionFr: 'Questions rapides pour valider la compréhension.',
        descriptionEn: 'Quick questions to validate understanding.',
        tipFr: 'Un quiz final renforce la mémorisation et identifie les lacunes.',
        tipEn: 'A final quiz reinforces memorization and identifies gaps.',
      },
    ],
  },
  {
    meetingType: 'autre',
    totalSlides: 8,
    durationMinFr: '15-30 min',
    durationMinEn: '15-30 min',
    slides: [
      {
        number: 1,
        titleFr: 'Page de titre',
        titleEn: 'Title Slide',
        descriptionFr: 'Titre, auteur, date, contexte de la réunion.',
        descriptionEn: 'Title, author, date, meeting context.',
        tipFr: 'Un titre clair évite les malentendus dès le départ.',
        tipEn: 'A clear title avoids misunderstandings from the start.',
      },
      {
        number: 2,
        titleFr: 'Objectif de la réunion',
        titleEn: 'Meeting Objective',
        descriptionFr: 'Pourquoi cette réunion a lieu et ce qu\'on en attend.',
        descriptionEn: 'Why this meeting is taking place and what is expected.',
        tipFr: 'Soyez explicite : informer, décider, brainstormer, aligner.',
        tipEn: 'Be explicit: inform, decide, brainstorm, align.',
      },
      {
        number: 3,
        titleFr: 'Contexte',
        titleEn: 'Context',
        descriptionFr: 'Éléments de contexte nécessaires à la compréhension du sujet.',
        descriptionEn: 'Context elements needed to understand the topic.',
        tipFr: 'Ne supposez pas que tout le monde a le même niveau d\'information.',
        tipEn: 'Don\'t assume everyone has the same level of information.',
      },
      {
        number: 4,
        titleFr: 'Contenu principal',
        titleEn: 'Main Content',
        descriptionFr: 'Le cœur du sujet, structuré en points clairs.',
        descriptionEn: 'The core of the topic, structured in clear points.',
        tipFr: 'Un message par slide. Si c\'est trop dense, découpez.',
        tipEn: 'One message per slide. If it\'s too dense, split it.',
      },
      {
        number: 5,
        titleFr: 'Points de discussion',
        titleEn: 'Discussion Points',
        descriptionFr: 'Questions ouvertes ou points nécessitant un échange.',
        descriptionEn: 'Open questions or points requiring discussion.',
        tipFr: 'Préparez les questions à l\'avance pour guider la discussion.',
        tipEn: 'Prepare questions in advance to guide the discussion.',
      },
      {
        number: 6,
        titleFr: 'Synthèse',
        titleEn: 'Summary',
        descriptionFr: 'Résumé des points clés abordés.',
        descriptionEn: 'Summary of key points covered.',
        tipFr: 'Répétez les messages essentiels pour ancrer la mémorisation.',
        tipEn: 'Repeat key messages to anchor memorization.',
      },
      {
        number: 7,
        titleFr: 'Prochaines étapes',
        titleEn: 'Next Steps',
        descriptionFr: 'Actions à mener avec responsables et délais.',
        descriptionEn: 'Actions to take with owners and deadlines.',
        tipFr: 'Une réunion sans prochaines étapes est une réunion inutile.',
        tipEn: 'A meeting without next steps is a useless meeting.',
      },
      {
        number: 8,
        titleFr: 'Questions',
        titleEn: 'Questions',
        descriptionFr: 'Temps dédié aux questions et échanges.',
        descriptionEn: 'Dedicated time for questions and exchanges.',
        tipFr: 'Gardez toujours du temps pour les questions.',
        tipEn: 'Always keep time for questions.',
      },
    ],
  },
]
